@startuml
title Domain Model

class User {
    +id: int
    +name: string
    +email: string
    +password_hash: string

}

class Event {
    +id: int
    +title: string
    +due_date: datetime
    +completed: bool
}

class Note {
    +id: int
    +content: string
    +created_at: datetime
    +updated_at: datetime
}

class Organization{
    +id: int
    +name: string
}

@enduml